### ISSUE TITLE
[How To Contribute] Url issues ведёт на локальный домен

### ISSUE THREAD

**Issue by obatsak** [Aerodisk/openvair#20]
В документе `https://github.com/Aerodisk/openvair/blob/main/CONTRIBUTING.md#how-to-contribute` в пункте 2 обе ссылки указывают локальный домен: `[issues](http://git.aerodisk.local/vair/openvair/-/issues)`

**Comment by tihon49** [comment]
Добрый день!
Спасибо за замечание. Поправим.

**Comment by Aerodisk** [comment]
Задача решена в рамках задачи по синхронизации кодовой базы с закрытой GitLab разработкой и полным переходом на разработку в GitHub:
PR: https://github.com/Aerodisk/openvair/pull/28
