### ISSUE TITLE
Настройка сети

### ISSUE THREAD

**Issue by 2lifehd** [Aerodisk/openvair#21]
Некорректно настраивается сетевой мост, после перезагрузки, интерфейс bridge не получает адрес по DHCP.
Использую получение динамического адреса, так что после перезагрузки не было доступа на сервер.
Желательно бы опцию, что бы была возможность назначить каким-то образом адрес на сетевой мост, или это адрес оставался на физическом интерфейсе.

**Comment by tihon49** [comment]
Добрый день!
Разобрались с данной проблемой. Наши рзработчики уже исправили. В ближайшее время зальем исправления.

**Comment by Aerodisk** [comment]
Задача решена в рамках задачи по синхронизации кодовой базы с закрытой GitLab разработкой и полным переходом на разработку в GitHub:
PR: https://github.com/Aerodisk/openvair/pull/28
