### ISSUE TITLE
[fix] Опечатка в файле README.ru.md

### ISSUE THREAD

**Issue by tihon49** [Aerodisk/openvair#29]
В разделе `"Настройка проекта"` опечатка в пути к файлу:
`/opt aero/openvair/project_config.toml`

Между `/opt` и положением стоит пробел, а должен быть slash - "`/`"

**Comment by Aerodisk** [comment]
PR: https://github.com/Aerodisk/openvair/pull/30/files

**Comment by tihon49** [comment]
PR: https://github.com/Aerodisk/openvair/pull/30/files
