### ISSUE TITLE
Добавить функцию execute_command как улучшенную альтернативу execute

### ISSUE THREAD

**Issue by VladimirTrue** [Aerodisk/openvair#42]
# **Обоснование задачи**

Текущая реализация функции `execute` не возвращает коды статуса выполнения команд, что приводит к трудностям обработки результатов. Новая функция должна устранить этот недостаток, предоставляя данные в удобном формате.

---

# **Описание задачи**

Реализовать функцию `execute_command`, которая:

- Возвращает код статуса выполнения команды.
- Типизирована согласно стандартам проекта.
- Предоставляет результаты выполнения команды в удобном для обработки формате.

Пример интерфейса функции:

```python
def execute_command(command: str) -> ExecutionResult:
    """
    Execute a CLI command and return its result.

    Args:
        command (str): The CLI command to execute.

    Returns:
        ExecutionResult: Object with return code, stdout, and stderr.
    """
```

### Описание `ExecutionResult`

Реализовать класс `ExecutionResult` с использованием Pydantic для удобной валидации и работы с результатами выполнения команды. Пример структуры:

```python
from pydantic import BaseModel

class ExecutionResult(BaseModel):
    returncode: int
    stdout: str
    stderr: str
```

Функцию необходимо разместить в файле `openvair/modules/tools/utils.py`. Существующая функция `execute` продолжает использоваться для сохранения обратной совместимости.

---

# **Требования к реализации**

1. Реализовать функцию `execute_command` в файле `openvair/modules/tools/utils.py`.
2. Создать класс `ExecutionResult` с использованием Pydantic для представления результата выполнения команды.
3. Подробно описать работу новой функции в docstring, добавив описание новой функции `execute_command` и модели `ExecutionResult`.

**Comment by tihon49** [comment]
Стоит учесть что новая команда, со временем, заместит старую. И мне кажется, что лучше бы, в итоге, оставить имя `execute`.

**Comment by VladimirTrue** [comment]
> Стоит учесть что новая команда, со временем, заместит старую. И мне кажется, что лучше бы, в итоге, оставить имя `execute`.

В процессе разработки решил так же, в итоговом варианте останется execute, который будет расположен в другом пакете

**Comment by VladimirTrue** [comment]
PR: https://github.com/Aerodisk/openvair/pull/46
